import pandas as pd
import statsmodels.formula.api as sm
import numpy as np
from sklearn.externals import joblib
from app.mod_db import *

def predict_all():
    """ 
    Populates all rows of the database with predicted occupancy counts generated by the predictive model
    (if they contain log data).
    """
    
    # Loads the serialised model. 
    lrm = joblib.load("model/model.pkl")

    #occ = int(round(lrm.predict(32)[0]))

    # Queries every row in the database containing a log file.
    results = Counts.select(Counts).where((Counts.counts_associated == 16.0))

    for result in results:
        print(result)
